Results of thread_exception_test:
Thread exception caught 'Operation failed'
